version: '3.3'
services:
  carts-api:
    container_name: carts-api
    build:
      context: cart
      dockerfile: Dockerfile
    image: carts-api:latest
    environment:
      - spring_profiles_active=production
    depends_on:
      - db
      - products-api
    ports:
      - 8002:8002
  products-api:
    container_name: products-api
    build:
      context: products
      dockerfile: Dockerfile
    image: products-api:latest
    environment:
      - spring_profiles_active=production
    depends_on:
      - db
    ports:
      - 8001:8001

  api-gateway:
    container_name: api-gateway
    image: nginx
    restart: always
    volumes:
      - ./production/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_shop_db
    volumes:
      - ./production/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./production/pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    ports:
      - "5050:80"